version: '3'
networks:
  paychan-server-network:
    driver: bridge
services:
  db:
    container_name: paychan_server_local_db
    image: mysql:8.0.30
    networks:
      - paychan-server-network
    ports:
      - 3306:3306
    volumes:
      - .conf/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: paychan_server_local
      MYSQL_ROOT_PASSWORD: password
  butler:
    build:
      context: .
      dockerfile: Dockerfile.local
    networks:
      - paychan-server-network
    volumes:
      - .:/go/src/app
    env_file:
      - .conf/local.env
    environment:
      APP_SERVICE: batch
      APP_BATCH_TYPE: butler
      DB_HOST: db
    depends_on:
      - db
    command: go run main.go
