// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hidenari-yuda/paychan-server/domain/config"
	"github.com/hidenari-yuda/paychan-server/interfaces"
	"github.com/hidenari-yuda/paychan-server/interfaces/handler"
	"github.com/hidenari-yuda/paychan-server/interfaces/repository"
	"github.com/hidenari-yuda/paychan-server/usecase"
	"github.com/hidenari-yuda/paychan-server/usecase/interactor"
)

// Injectors from wire.go:

//Admin
//
func InitializeAdminHandler(db interfaces.SQLExecuter, appConfig config.App) handler.AdminHandler {
	adminInteractor := interactor.NewAdminInteractorImpl(appConfig)
	adminHandler := handler.NewAdminHandlerImpl(adminInteractor)
	return adminHandler
}

// User
//
func InitializeUserHandler(db interfaces.SQLExecuter, fb usecase.Firebase) handler.UserHandler {
	userRepository := repository.NewUserRepositoryImpl(db)
	receiptPictureRepository := repository.NewReceiptPictureRepositoryImpl(db)
	receiptRepository := repository.NewReceiptRepositoryImpl(db)
	parchasedItemRepository := repository.NewParchasedItemRepositoryImpl(db)
	paymentMethodRepository := repository.NewPaymentMethodRepositoryImpl(db)
	presentRepository := repository.NewPresentRepositoryImpl(db)
	lineMessageRepository := repository.NewLineMessageRepositoryImpl(db)
	adRepository := repository.NewAdRepositoryImpl(db)
	userInteractor := interactor.NewUserInteractorImpl(fb, userRepository, receiptPictureRepository, receiptRepository, parchasedItemRepository, paymentMethodRepository, presentRepository, lineMessageRepository, adRepository)
	userHandler := handler.NewUserHandlerImpl(userInteractor)
	return userHandler
}

// Present
//
func InitializePresentHandler(db interfaces.SQLExecuter, fb usecase.Firebase) handler.PresentHandler {
	userRepository := repository.NewUserRepositoryImpl(db)
	receiptPictureRepository := repository.NewReceiptPictureRepositoryImpl(db)
	receiptRepository := repository.NewReceiptRepositoryImpl(db)
	parchasedItemRepository := repository.NewParchasedItemRepositoryImpl(db)
	paymentMethodRepository := repository.NewPaymentMethodRepositoryImpl(db)
	presentRepository := repository.NewPresentRepositoryImpl(db)
	lineMessageRepository := repository.NewLineMessageRepositoryImpl(db)
	adRepository := repository.NewAdRepositoryImpl(db)
	presentInteractor := interactor.NewPresentInteractorImpl(fb, userRepository, receiptPictureRepository, receiptRepository, parchasedItemRepository, paymentMethodRepository, presentRepository, lineMessageRepository, adRepository)
	presentHandler := handler.NewPresentHandlerImpl(presentInteractor)
	return presentHandler
}

//Admin
//
func InitializeAdminInteractor(db interfaces.SQLExecuter, appConfig config.App) interactor.AdminInteractor {
	adminInteractor := interactor.NewAdminInteractorImpl(appConfig)
	return adminInteractor
}

// User
//
func InitializeUserInteractor(db interfaces.SQLExecuter, fb usecase.Firebase) interactor.UserInteractor {
	userRepository := repository.NewUserRepositoryImpl(db)
	receiptPictureRepository := repository.NewReceiptPictureRepositoryImpl(db)
	receiptRepository := repository.NewReceiptRepositoryImpl(db)
	parchasedItemRepository := repository.NewParchasedItemRepositoryImpl(db)
	paymentMethodRepository := repository.NewPaymentMethodRepositoryImpl(db)
	presentRepository := repository.NewPresentRepositoryImpl(db)
	lineMessageRepository := repository.NewLineMessageRepositoryImpl(db)
	adRepository := repository.NewAdRepositoryImpl(db)
	userInteractor := interactor.NewUserInteractorImpl(fb, userRepository, receiptPictureRepository, receiptRepository, parchasedItemRepository, paymentMethodRepository, presentRepository, lineMessageRepository, adRepository)
	return userInteractor
}

// Present
//
func InitializePresentInteractor(db interfaces.SQLExecuter, fb usecase.Firebase) interactor.PresentInteractor {
	userRepository := repository.NewUserRepositoryImpl(db)
	receiptPictureRepository := repository.NewReceiptPictureRepositoryImpl(db)
	receiptRepository := repository.NewReceiptRepositoryImpl(db)
	parchasedItemRepository := repository.NewParchasedItemRepositoryImpl(db)
	paymentMethodRepository := repository.NewPaymentMethodRepositoryImpl(db)
	presentRepository := repository.NewPresentRepositoryImpl(db)
	lineMessageRepository := repository.NewLineMessageRepositoryImpl(db)
	adRepository := repository.NewAdRepositoryImpl(db)
	presentInteractor := interactor.NewPresentInteractorImpl(fb, userRepository, receiptPictureRepository, receiptRepository, parchasedItemRepository, paymentMethodRepository, presentRepository, lineMessageRepository, adRepository)
	return presentInteractor
}

// wire.go:

var wireSet = wire.NewSet(handler.WireSet, interactor.WireSet, repository.WireSet)
